min_python: 3.5.0
log_file: /var/log/vHunter/vHunter.log
log_level: DEBUG
log_format: "[%(asctime)s %(funcName)s] %(message)s"

scenarios_dirs: 
    - /etc/vHunter
    - /Users/evemorgen/scenarios
supported_platforms:
    - mac_os
    - linux
commands:
    - fallback_distro_command: 'cat /etc/*release | grep -P "(^ID=.*)|(^VERSION_ID=.*)"'

